//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstMVCProjem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int cardID { get; set; }
        public string cardType { get; set; }
        public Nullable<decimal> cardLimit { get; set; }
        public Nullable<int> accountNo { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
